# Generated by Django 2.0.6 on 2018-06-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank',
            field=models.CharField(default='bank', max_length=50),
            preserve_default=False,
        ),
    ]
