# Generated by Django 2.0.6 on 2018-06-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='bank', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='expected_loss',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='probability_of_default',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='title',
            field=models.CharField(default='loan', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Bank'),
        ),
    ]
