# Generated by Django 2.0.6 on 2018-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20180614_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='expected_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='probability_of_default',
            field=models.FloatField(default=0.0),
        ),
    ]
