# Generated by Django 2.0.6 on 2018-06-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20180619_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='owner',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
