# Generated by Django 2.0.6 on 2018-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='saleable',
            field=models.BooleanField(default=True),
        ),
    ]
