# Generated by Django 2.0.6 on 2018-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auto_20180620_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='el_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loan',
            name='pd_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='owner',
            field=models.CharField(default='0.0.0.0', max_length=200),
        ),
    ]
