# Generated by Django 2.0.6 on 2018-06-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20180621_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='title',
            new_name='name',
        ),
    ]
