# Generated by Django 2.0.6 on 2018-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20180622_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='saleable',
            field=models.IntegerField(default=1),
        ),
    ]
